### ISSUE TITLE
Mod not visible in steam workshop

### ISSUE THREAD

**Issue by adrian-kurzeja** [Blockaroz/CalamityHunt#11]
Not sure where to add this problem so I am adding it here. Today for some reason mod disappeared from steam workshop (at least for me). Steam automatically removed `.tmod` file, and I can't load my save. 

I checked tmodloader logs files, and yesterday `calamityhunt` loaded normally, and today it is just gone.

Could you either check why steam again decided to break something? Or give me a clue how can I fix this problem?

Maybe publish on repo latest `.tmod` file? I can't find it anywhere. Would be great. 

Will appreciate any help! Thank you!

**Comment by Theyoungster** [comment]
Yeah, I noticed this too. Was it manually deleted?

**Comment by TohruKobayashi** [comment]
mod was taken off the browser by blockaroz, dev team is currently investigating a solution. if you wanna play with the mod, theres a [download](https://www.mediafire.com/file/jimacjkbbg12cul/CalamityHunt.tmod/file) on the [wiki](https://terrariamods.wiki.gg/wiki/Hunt_of_the_Old_God), its the best we can do right now. if you dont know how to manually install, take the tmod file and put it in your mods folder (Documents\My Games\Terraria\tModLoader\Mods). we apologize for the inconvenience

**Comment by steviegt6** [comment]
this is so SAD

**Comment by Theyoungster** [comment]
> this is so SAD

<sub>Despacito, play Country Road</sub>

**Comment by Theyoungster** [comment]
Hey, it's back! Someone mark this as resolved
